config/routes.rb
Quiz1::Application.routes.draw do
  root 'posts#index'
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: :show

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to post_path(@post)
  end

  def show

  end


  private

  def post_params
    params.require(:post).permit(:title, :description)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Quiz 1 Page</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<body>
  <section id="page">
        <header>
            <hgroup>
                <h1><%= link_to "Saroar Khandoker" , root_path %></h1>
                <h3>Junior Full Stack Web Developer</h3>
            </hgroup>
            <nav class="clear">
                <ul>
                    <li><%= link_to "Add Article", new_post_path %></li>
                    <li><%= link_to "FireHouse", "http://www.thefirehoseproject.com" %></li>
                    <li><%= link_to "iBlog", "http://community.thefirehoseproject.com" %></li>
                    <li><%= link_to "contact", "http://community.thefirehoseproject.com/contact/" %></li>
                </ul>
            </nav>
        </header>
        <% @posts.each do |post| %>
          <section id="articles">
            <div class="line"></div>
              <article id="article1">

                  <h2><%= post.title %></h2>

                  <div class="line"></div>

                  <div class="articleBody clear">

                    <figure>
                      <%= link_to "http://community.thefirehoseproject.com/2015/09/10/chris-mcintyre-shows-the-basics-pry-for-rails.html" do %>
                        <%= image_tag 'pry_logo.png',  width: 620, height: 340 %>
                      <% end %>
                      </figure>
                      <p><%= post.description %></p>
                      <p></p>
                  </div>
          </section>
        <% end %>

    <footer>
       <div class="line"></div>
       <p>Copyright 2015 - SaroarKhandoker</p>
    </footer>

</section>

</body>
</html>

app/views/posts/new.html.erb
<section id="articles">
    <article id="article1">
      <%= simple_form_for @post do |f| %>
        <%= f.input :title%>
        <%= f.input :description  %>
        <br />
        <%= f.submit "Create" %>
      <% end %>
    </article>
</section>

app/views/posts/show.html.erb
<section id="articles">
  <h1><%= @post.title %></h1>
  <p><%= @post.description %></p>
</section>

app/views/static_pages/index.html.erb
    <body>
    	<section id="page">
            <header>
                <hgroup>
                    <h1>Saroar Khandoker</h1>
                    <h3>Junior Full Stack Web Developer</h3>
                </hgroup>
                <nav class="clear">
                    <ul>
												<li><%= link_to "FireHouse", "http://www.thefirehoseproject.com" %></li>
                        <li><%= link_to "iBlog", "http://community.thefirehoseproject.com" %></li>
                        <li><%= link_to "contact", "http://community.thefirehoseproject.com/contact/" %></li>
                    </ul>
                </nav>
            </header>

            <section id="articles">
				      <div class="line"></div>
                <article id="article1">
                    <h2>Pry Open Rails</h2>

                    <div class="line"></div>

                    <div class="articleBody clear">

                    	<figure>
	                    	<%= link_to "http://community.thefirehoseproject.com/2015/09/10/chris-mcintyre-shows-the-basics-pry-for-rails.html" do %>
													<%= image_tag 'pry_logo.png',  width: 620, height: 340 %>
												<% end %>
                        </figure>
												<p>Chris is an aspiring developer, a bit obsessed with coding, and an alumni of theFirehoseProject. After struggling with debugging code in IRB, her mentor clued her in on the better way to debug. Enter Pry! It’s a powerful tool… it’s IRB with superpowers! Stop dreading debugging…Pry open Rails and get it done!</p>
                    </div>
                </article>


                <div class="line"></div>

                <article id="article2">
                    <h2>Reading Code You Didn't Write</h2>

                    <div class="line"></div>

                    <div class="articleBody clear">
                    	<figure>
												<%= link_to "http://community.thefirehoseproject.com/2015/08/20/mikaila-waters-reading-code-you-didnt-write.html" do %>
													<%= image_tag 'reading-code-you-didnt-write.jpg',  width: 620, height: 340 %>
												<% end %>
                        </figure>
												<p>Mikaila is a current student in the Firehose Project curriculum and works at an edtech startup called Gradeable on all aspects of the product. She started at Gradeable as the designer, and then taught herself HTML, CSS, and a smudge of Javascript, because there was work to be done.

Mikaila walks you through the process she used to understand her company’s code before she understood code, and why collaborating with other developers will make you a much stronger developer than trying to go it alone.</p>
                    </div>
                </article>
            </section>

        <footer>
           <div class="line"></div>
           <p>Copyright 2015 - SaroarKhandoker</p>
        </footer>

		</section>

    </body>
</html>